### ISSUE TITLE
GCMS-Bruno-Holder

### ISSUE THREAD

**Issue by BrunoHldr** [BrunoHldr/GCMS-Bruno-Holder#1]
[README.md](https://github.com/BrunoHldr/GCMS-Bruno-Holder/edit/main/README.md)

**Comment by BrunoHldr** [comment]
@ramidedantas

**Comment by ramidedantas** [comment]
@BrunoHldr 

O nome do seu repositório não segue o padrão da prática, veja as instruções lá e veja se consegue mudar.

Deixe no seu Readme apenas com você como colaborador, adiciono meu nome depois. Me marque aqui quando fizer.

**Comment by BrunoHldr** [comment]
@ramidedantas

**Comment by ramidedantas** [comment]
@BrunoHldr o nome do repositorio está OK agora, mas o está faltando criar o Readme (veja instruções na página do repositório, abaixo do link). O seu link na issue está apontando para a propria issue.

**Comment by ramidedantas** [comment]
@BrunoHldr readme alterado.
